name: pytorch-ci
channels:
  - pytorch
dependencies:
  - python = 3.6
  - pytorch = 1.0.1
  - cudatoolkit = 9.2
  - pip
  - torchvision
  - nose
  - numpy
  - cython
  - scipy
  - networkx
  - matplotlib
  - nltk
  - requests[security]
  - tqdm