name: Pylint

on: [push]

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PyTorch
        uses: actions/checkout@v3
      - name: Run flake8
        uses: TrueBrain/actions-flake8@v2
